### ISSUE TITLE
Document that Folding@Home is an alternative

### ISSUE THREAD

**Issue by ssb22** [Drag-NDrop/OCIScripts#2] opened 2023-09-13 21:50 UTC
Given the README comments about climate change and useless work, I wonder if it might be slightly less bad to do *useful* work, and this could be mentioned in the Readme as another option to consider?

Oracle's terms of use say no crypto mining, but they don't seem to prohibit other long-running processes at this time, and I particularly mention [Folding@Home](https://foldingathome.org/) because [Oracle's Principal Cloud Architect blogged about it in 2021](https://blogs.oracle.com/cloud-infrastructure/post/how-to-deploy-foldinghome-in-oracle-cloud-infrastructure) so I assume they think that one's OK (it is after all helping medical research).  If you're running Ubuntu on OCI, it's sufficient to `wget` the `fahclient` deb file using the latest link on Folding@Home's "all downloads" page (choose x86 or ARM as appropriate), then run `sudo apt install ./fahclient_*deb` and accept all default settings (except I set the folding level to "light") and the package scripts will take care of the rest.

I have tested that Folding@Home's CPU usage *does* count as "CPU utilisation" on the OCI dashboard (i.e. that measure doesn't make exceptions for low-priority processes or anything like that).

To save energy as well, you could have a schedule to pause and unpause the computation using the FAHClient "send" options from any user account on the box.  I wouldn't recommend using `--send-pause` much because (especially on a low-spec instance) it means your assigned work unit will be "checked out" for longer than normal and might miss Folding@Home's completion deadline, which means it'll be reassigned to someone else, so we'd be back to "running the CPU for nothing" and also being unhelpful to Folding@Home by checking out work units and not finishing them on time.  But there is the command `FAHClient --send-finish` which means "finish our current work unit and *then* stop", so for example you could put into `crontab -e` a "daily dose" of Folding@Home:

    0 2 * * * FAHClient --send-unpause
    0 3 * * * FAHClient --send-finish

meaning "start work at 02:00 and finish some time after 03:00" although some jobs can take hours to finish.  Or if you prefer you can set a schedule that works on a weekly basis: I assume the rule "CPU utilisation for the 95th percentile is less than N" over 7 days means you need about 8½ hours a week, so one 8-hour run per week that ends with a `--send-finish` should be more than adequate.

(Disclosure: I currently happen to have a job working for Oracle, but it's not in the department that runs OCI.  Opinions here are my own and not those of Oracle which has not checked what I said.)

**Comment by Drag-NDrop** [comment] 2023-09-16 15:24
I really like these thoughts. I abandoned OCI a while back, because they started to remove my S2S VPN’s with no reason.

This might pull me back. It’s an interesting take, and another shot at having a free computer connected to the home network.

Thanks a lot for the input!

Fra: Silas S. Brown ***@***.***>
Sendt: 13. september 2023 23:51
Til: Drag-NDrop/OCIScripts ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [Drag-NDrop/OCIScripts] Document that ***@***.*** is an alternative (Issue #2)


Given the README comments about climate change and useless work, I wonder if it might be slightly less bad to do useful work, and this could be mentioned in the Readme as another option to consider?

Oracle's terms of use say no crypto mining, but they don't seem to prohibit other long-running processes at this time, and I particularly mention ***@***.***<https://foldingathome.org/> because Oracle's Principal Cloud Architect blogged about it in 2021<https://blogs.oracle.com/cloud-infrastructure/post/how-to-deploy-foldinghome-in-oracle-cloud-infrastructure> so I assume they think that one's OK (it is after all helping medical research). If you're running Ubuntu on OCI, it's sufficient to wget the fahclient deb file using the latest link on ***@***.***'s "all downloads" page (choose x86 or ARM as appropriate), then run sudo apt install ./fahclient_*deb and accept all default settings (except I set the folding level to "light") and the package scripts will take care of the rest.

I have tested that ***@***.***'s CPU usage does count as "CPU utilisation" on the OCI dashboard (i.e. that measure doesn't make exceptions for low-priority processes or anything like that).

To save energy as well, you could have a schedule to pause and unpause the computation using the FAHClient "send" options from any user account on the box. I wouldn't recommend using --send-pause much because (especially on a low-spec instance) it means your assigned work unit will be "checked out" for longer than normal and might miss ***@***.***'s completion deadline, which means it'll be reassigned to someone else, so we'd be back to "running the CPU for nothing" and also being unhelpful to ***@***.*** by checking out work units and not finishing them on time. But there is the command FAHClient --send-finish which means "finish our current work unit and then stop", so for example you could put into crontab -e a "daily dose" of ***@***.***:

0 2 * * * FAHClient --send-unpause

0 3 * * * FAHClient --send-finish

meaning "start work at 02:00 and finish some time after 03:00" although some jobs can take hours to finish. Or if you prefer you can set a schedule that works on a weekly basis: I assume the rule "CPU utilisation for the 95th percentile is less than N" over 7 days means you need about 8½ hours a week, so one 8-hour run per week that ends with a --send-finish should be more than adequate.

(Disclosure: I currently happen to have a job working for Oracle, but it's not in the department that runs OCI. Opinions here are my own and not those of Oracle which has not checked what I said.)

**Comment by krlc** [comment] 2023-10-12 10:33
What kind of S2S VPNs were you using? What kind of setup? I'm using Tailscale to connect multiple instances in and outside OCI, so I'm wondering if I should be worried

**Comment by Drag-NDrop** [comment] 2023-10-12 17:54
> What kind of S2S VPNs were you using? What kind of setup? I'm using Tailscale to connect multiple instances in and outside OCI, so I'm wondering if I should be worried

I was using the S2S VPN configuration that can be set up directly in the OCI interface.
I was hosting a Wiki.js instance, and a n8n instance.
Admittedly, i didn't use them a lot. But i really liked having those available to me.

I never really expected this git to light up like this.
So i'm coming back to this project soon. I'll be re-writing it to use Powershell Core. It's an area of expertise of mine in Windows environments. And I'm quite interested to find out how Powershell works on Debian nowadays.

Anyone reading this, who could be interested in collab - let me know. Perhaps organize on a Discord server. No need for voice chat as I'm not a big fan of it. But a direct chat to query for opinions and tests, could be mad cool.

**Comment by Codycody31** [comment] 2023-10-23 14:47
Hey @Drag-NDrop, wasn't sure how to contact you, not sure if this would be the correct way. I was able to get a discord guild setup if you would want to use that: https://discord.gg/HRNVF5Tf9a. I'd love to help out, though I don't have any experience with Powershell. I've been using this script on a few of my servers so I would love to help progress it in some way.

**Comment by Drag-NDrop** [comment] 2023-10-23 21:04
> Hey @Drag-NDrop, wasn't sure how to contact you, not sure if this would be the correct way. I was able to get a discord guild setup if you would want to use that: https://discord.gg/HRNVF5Tf9a. I'd love to help out, though I don't have any experience with Powershell. I've been using this script on a few of my servers so I would love to help progress it in some way.

Great initiative! Let's get to it! :D

**Comment by Fummowo** [comment] 2023-10-28 23:16
Thank you for this idea! Always felt bad wasting free resources so I span up a Folding@Home docker container and limited its cpu :)) would be nice to see an even more optimised version of this solution though! I'm probably going to upgrade to a paid account to get past the Idle limits but still only use the free resources in the near future but will be nice to see others make better use of the cpu :)

**Comment by Drag-NDrop** [comment] 2023-10-29 11:00
> Thank you for this idea! Always felt bad wasting free resources so I span up a Folding@Home docker container and limited its cpu :)) would be nice to see an even more optimised version of this solution though! I'm probably going to upgrade to a paid account to get past the Idle limits but still only use the free resources in the near future but will be nice to see others make better use of the cpu :)

Hey Fummowo :)

Thanks for letting me know! Great that other people feels the same way.
During my research, i found that Folding@Home is not the best fit for OCI instances(their workunits are to big).

I'm currently prototyping a Boinc installer instead. Same concept, just helping out a University in Warzaw by doing calculations of space instead :)

Let me know if you could be interested in helping testing it :)

**Comment by Drag-NDrop** [comment] 2023-11-04 14:28
The prototype that came out of the research is now live.
It can be found here: https://github.com/Drag-NDrop/IdleRunner

The project "Universe" from the University of Warzaw, Poland, fit the usecase the best.
It's currently in its beta test phase, and we have confirmed it works as expected on both Ubuntu and Debian instances.

It basically replaces the contents of this repo 1-1, and offers much more gain to the world, than this original repo ever did. I recommend it.

**Comment by ssb22** [comment] 2023-11-04 15:29
Thanks.  Let's not forget also that OCI has both AMD64 and ARM machines, and a lot of the "what's the best workload to run" discussion may depend on which architecture the user has chosen (AMD64 or ARM).

Currently, in the Free Tier, AMD64 gives you 2 virtual cores (actually 1 real core with 2-way hyperthreading) at 2GHz, and 1 Gigabyte of RAM, whereas ARM gives you up to 4 real cores at 3GHz, and 24 Gigabytes of RAM.  (Pretty sure they wanted to promote migrating to ARM.)

Folding@Home can work on both AMD64 and ARM, and Universe@Home says it can work on ARM as well (I haven't tested this myself).  I don't know if all their work units can work on any architecture, or if there are some "AMD64-only work units" out there.

Folding@Home has a range of work unit sizes.  The work server tries to assign you a unit that's appropriate for your hardware.  So if you have a top-of-the-range GPU setup, you're likely to get the biggest units, whereas a simple CPU-only machine is likely to get only smaller units.  OCI Free Tier machines are CPU-only (no GPU), so they can take only the smaller work units.

If you install Folding@Home on an OCI AMD64 instance and leave it at the default "light" configuration, Folding@Home will interpret this as "don't use all the cores", and as these instances have only 2 virtual cores, that means it will limit itself to just 1 core.  That in turn means it will not accept any work unit that requires more than one core.  So it is possible for an OCI AMD64 Free Tier machine with Folding@Home set to "light" to actually idle for some time until a work unit becomes available that can be done with a single core (the Folding@Home server doesn't always have one of those ready when you want one, so you might have to wait).  To work around this, you could change `/etc/fahclient/config.xml` to say `<power v='full'/>` and make _both_ virtual cores available to Folding@Home: this is likely to result in work units being available more frequently (at least for now), but don't forget you actually have two _virtual_ cores running on the same _real_ core, and that means accepting a two-core work unit will likely land you with more than one day of continuous running before it's finished, which leaves less time to be able to pause it without being too late to return the results.

The ARM boxes are a different story: a Folding@Home work unit is typically finished within hours on those boxes.  I've found I can set my crontab to do one unit starting in the early hours of the morning and the box will be idle by mid-morning, even if I limit it to only 2 of the 4 cores.

So, as of now (might change in future), you _can_ run Folding@Home on both AMD64 and ARM instances in OCI Free Tier, but if you'd rather have shorter work units then you might prefer a project with those _especially if you're on AMD64_ (it doesn't make as much difference on ARM right now).

The other reason why I mentioned Folding@Home in particular is because that's what was on the Oracle blog.  I have no special inside information about this whatsoever, but I'm _guessing_ that if they blogged about it then they're less likely to suddenly turn around and decide it's not an acceptable use of OCI Free Tier.  Well hopefully if they _did_ decide to say "don't do distributed computing unless the project is one we've approved", then they'd give us some warning first and maybe even take requests for other projects to be added to the approved list, but going for one that we already know is likely to be OK might mean less hassle later.  But this _does_ need to be balanced against the consideration of Folding@Home work units now being bigger than they used to be, which is especially noticeable on the AMD64 instances.

**Closed as completed** 2023-11-06 09:42 UTC
